/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ac.blitz.acme;

public class ChannelStatisticArray {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ChannelStatisticArray(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ChannelStatisticArray obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ACMEJNI.delete_ChannelStatisticArray(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ChannelStatisticArray() {
    this(ACMEJNI.new_ChannelStatisticArray__SWIG_0(), true);
  }

  public ChannelStatisticArray(long n) {
    this(ACMEJNI.new_ChannelStatisticArray__SWIG_1(n), true);
  }

  public long size() {
    return ACMEJNI.ChannelStatisticArray_size(swigCPtr, this);
  }

  public long capacity() {
    return ACMEJNI.ChannelStatisticArray_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    ACMEJNI.ChannelStatisticArray_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return ACMEJNI.ChannelStatisticArray_isEmpty(swigCPtr, this);
  }

  public void clear() {
    ACMEJNI.ChannelStatisticArray_clear(swigCPtr, this);
  }

  public void add(ChannelStatistic x) {
    ACMEJNI.ChannelStatisticArray_add(swigCPtr, this, ChannelStatistic.getCPtr(x), x);
  }

  public ChannelStatistic get(int i) {
    return new ChannelStatistic(ACMEJNI.ChannelStatisticArray_get(swigCPtr, this, i), false);
  }

  public void set(int i, ChannelStatistic val) {
    ACMEJNI.ChannelStatisticArray_set(swigCPtr, this, i, ChannelStatistic.getCPtr(val), val);
  }

}
