/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ac.blitz.acme;

public class ChannelDumpArray {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ChannelDumpArray(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ChannelDumpArray obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ACMEJNI.delete_ChannelDumpArray(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ChannelDumpArray() {
    this(ACMEJNI.new_ChannelDumpArray__SWIG_0(), true);
  }

  public ChannelDumpArray(long n) {
    this(ACMEJNI.new_ChannelDumpArray__SWIG_1(n), true);
  }

  public long size() {
    return ACMEJNI.ChannelDumpArray_size(swigCPtr, this);
  }

  public long capacity() {
    return ACMEJNI.ChannelDumpArray_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    ACMEJNI.ChannelDumpArray_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return ACMEJNI.ChannelDumpArray_isEmpty(swigCPtr, this);
  }

  public void clear() {
    ACMEJNI.ChannelDumpArray_clear(swigCPtr, this);
  }

  public void add(ChannelDump x) {
    ACMEJNI.ChannelDumpArray_add(swigCPtr, this, ChannelDump.getCPtr(x), x);
  }

  public ChannelDump get(int i) {
    return new ChannelDump(ACMEJNI.ChannelDumpArray_get(swigCPtr, this, i), false);
  }

  public void set(int i, ChannelDump val) {
    ACMEJNI.ChannelDumpArray_set(swigCPtr, this, i, ChannelDump.getCPtr(val), val);
  }

}
