/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ac.blitz.acme;

public final class EngineCapacity {
  public final static EngineCapacity CAP_AUDIO = new EngineCapacity("CAP_AUDIO", ACMEJNI.CAP_AUDIO_get());
  public final static EngineCapacity CAP_VIDEO = new EngineCapacity("CAP_VIDEO", ACMEJNI.CAP_VIDEO_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static EngineCapacity swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + EngineCapacity.class + " with value " + swigValue);
  }

  private EngineCapacity(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private EngineCapacity(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private EngineCapacity(String swigName, EngineCapacity swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static EngineCapacity[] swigValues = { CAP_AUDIO, CAP_VIDEO };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

