/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ac.blitz.acme;

public class EngineInitializeEvent extends EngineEvent {
  private long swigCPtr;

  public EngineInitializeEvent(long cPtr, boolean cMemoryOwn) {
    super(ACMEJNI.EngineInitializeEvent_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EngineInitializeEvent obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @Override
protected void finalize() {
    delete();
  }

  @Override
public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ACMEJNI.delete_EngineInitializeEvent(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static String TypeName() {
    return ACMEJNI.EngineInitializeEvent_TypeName();
  }

  @Override
public String EventName() {
    return ACMEJNI.EngineInitializeEvent_EventName(swigCPtr, this);
  }

  public void setCode(int value) {
    ACMEJNI.EngineInitializeEvent_Code_set(swigCPtr, this, value);
  }

  public int getCode() {
    return ACMEJNI.EngineInitializeEvent_Code_get(swigCPtr, this);
  }

  public EngineInitializeEvent() {
    this(ACMEJNI.new_EngineInitializeEvent(), true);
  }

}
