/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ac.blitz.acme;

public class EngineEventListener {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected EngineEventListener(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EngineEventListener obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ACMEJNI.delete_EngineEventListener(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    ACMEJNI.EngineEventListener_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    ACMEJNI.EngineEventListener_change_ownership(this, swigCPtr, true);
  }

  public void OnEvent(EngineEvent ev) {
    ACMEJNI.EngineEventListener_OnEvent(swigCPtr, this, EngineEvent.getCPtr(ev), ev);
  }

  public EngineEventListener() {
    this(ACMEJNI.new_EngineEventListener(), true);
    ACMEJNI.EngineEventListener_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
