/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ac.blitz.acme;

public class EngineFirstPictureEvent extends EngineEvent {
  private long swigCPtr;

  protected EngineFirstPictureEvent(long cPtr, boolean cMemoryOwn) {
    super(ACMEJNI.EngineFirstPictureEvent_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EngineFirstPictureEvent obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ACMEJNI.delete_EngineFirstPictureEvent(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static String TypeName() {
    return ACMEJNI.EngineFirstPictureEvent_TypeName();
  }

  public String EventName() {
    return ACMEJNI.EngineFirstPictureEvent_EventName(swigCPtr, this);
  }

  public void setUserId(String value) {
    ACMEJNI.EngineFirstPictureEvent_UserId_set(swigCPtr, this, value);
  }

  public String getUserId() {
    return ACMEJNI.EngineFirstPictureEvent_UserId_get(swigCPtr, this);
  }

  public EngineFirstPictureEvent() {
    this(ACMEJNI.new_EngineFirstPictureEvent(), true);
  }

}
