/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ac.blitz.acme;

public class EngineConfig {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected EngineConfig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EngineConfig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ACMEJNI.delete_EngineConfig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTrace(String value) {
    ACMEJNI.EngineConfig_trace_set(swigCPtr, this, value);
  }

  public String getTrace() {
    return ACMEJNI.EngineConfig_trace_get(swigCPtr, this);
  }

  public void setUserId(String value) {
    ACMEJNI.EngineConfig_userId_set(swigCPtr, this, value);
  }

  public String getUserId() {
    return ACMEJNI.EngineConfig_userId_get(swigCPtr, this);
  }

  public void setToken(UInt8Array value) {
    ACMEJNI.EngineConfig_token_set(swigCPtr, this, UInt8Array.getCPtr(value), value);
  }

  public UInt8Array getToken() {
    long cPtr = ACMEJNI.EngineConfig_token_get(swigCPtr, this);
    return (cPtr == 0) ? null : new UInt8Array(cPtr, false);
  }

  public void setLbs(String value) {
    ACMEJNI.EngineConfig_lbs_set(swigCPtr, this, value);
  }

  public String getLbs() {
    return ACMEJNI.EngineConfig_lbs_get(swigCPtr, this);
  }

  public void setAndroidJavaVM(Object value) {
    ACMEJNI.EngineConfig_androidJavaVM_set(swigCPtr, this, value);
  }


  public void setAndroidEnv(Object value) {
    ACMEJNI.EngineConfig_androidEnv_set(swigCPtr, this, value);
  }



  public void setAndroidContext(Object value) {
    ACMEJNI.EngineConfig_androidContext_set(swigCPtr, this, value);
  }



  public EngineConfig() {
    this(ACMEJNI.new_EngineConfig(), true);
  }

}
