/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ac.blitz.acme;

public class EngineMediaPublishStatusEvent extends EngineEvent {
  private long swigCPtr;

  protected EngineMediaPublishStatusEvent(long cPtr, boolean cMemoryOwn) {
    super(ACMEJNI.EngineMediaPublishStatusEvent_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EngineMediaPublishStatusEvent obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ACMEJNI.delete_EngineMediaPublishStatusEvent(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static String TypeName() {
    return ACMEJNI.EngineMediaPublishStatusEvent_TypeName();
  }

  public String EventName() {
    return ACMEJNI.EngineMediaPublishStatusEvent_EventName(swigCPtr, this);
  }

  public void setUserId(String value) {
    ACMEJNI.EngineMediaPublishStatusEvent_UserId_set(swigCPtr, this, value);
  }

  public String getUserId() {
    return ACMEJNI.EngineMediaPublishStatusEvent_UserId_get(swigCPtr, this);
  }

  public void setType(MediaType value) {
    ACMEJNI.EngineMediaPublishStatusEvent_Type_set(swigCPtr, this, value.swigValue());
  }

  public MediaType getType() {
    return MediaType.swigToEnum(ACMEJNI.EngineMediaPublishStatusEvent_Type_get(swigCPtr, this));
  }

  public void setAction(MediaPublishStatus value) {
    ACMEJNI.EngineMediaPublishStatusEvent_Action_set(swigCPtr, this, value.swigValue());
  }

  public MediaPublishStatus getAction() {
    return MediaPublishStatus.swigToEnum(ACMEJNI.EngineMediaPublishStatusEvent_Action_get(swigCPtr, this));
  }

  public EngineMediaPublishStatusEvent() {
    this(ACMEJNI.new_EngineMediaPublishStatusEvent(), true);
  }

}
