/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ac.blitz.acme;

public class EngineALREvent extends EngineEvent {
  private long swigCPtr;

  protected EngineALREvent(long cPtr, boolean cMemoryOwn) {
    super(ACMEJNI.EngineALREvent_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EngineALREvent obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ACMEJNI.delete_EngineALREvent(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static String TypeName() {
    return ACMEJNI.EngineALREvent_TypeName();
  }

  public String EventName() {
    return ACMEJNI.EngineALREvent_EventName(swigCPtr, this);
  }

  public void setUserId(String value) {
    ACMEJNI.EngineALREvent_UserId_set(swigCPtr, this, value);
  }

  public String getUserId() {
    return ACMEJNI.EngineALREvent_UserId_get(swigCPtr, this);
  }

  public void setLevel(int value) {
    ACMEJNI.EngineALREvent_Level_set(swigCPtr, this, value);
  }

  public int getLevel() {
    return ACMEJNI.EngineALREvent_Level_get(swigCPtr, this);
  }

  public void setRange(int value) {
    ACMEJNI.EngineALREvent_Range_set(swigCPtr, this, value);
  }

  public int getRange() {
    return ACMEJNI.EngineALREvent_Range_get(swigCPtr, this);
  }

  public EngineALREvent() {
    this(ACMEJNI.new_EngineALREvent(), true);
  }

}
