/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ac.blitz.acme;

public class Int8Array {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Int8Array(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Int8Array obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ACMEJNI.delete_Int8Array(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Int8Array() {
    this(ACMEJNI.new_Int8Array__SWIG_0(), true);
  }

  public Int8Array(long n) {
    this(ACMEJNI.new_Int8Array__SWIG_1(n), true);
  }

  public long size() {
    return ACMEJNI.Int8Array_size(swigCPtr, this);
  }

  public long capacity() {
    return ACMEJNI.Int8Array_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    ACMEJNI.Int8Array_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return ACMEJNI.Int8Array_isEmpty(swigCPtr, this);
  }

  public void clear() {
    ACMEJNI.Int8Array_clear(swigCPtr, this);
  }

  public void add(byte x) {
    ACMEJNI.Int8Array_add(swigCPtr, this, x);
  }

  public byte get(int i) {
    return ACMEJNI.Int8Array_get(swigCPtr, this, i);
  }

  public void set(int i, byte val) {
    ACMEJNI.Int8Array_set(swigCPtr, this, i, val);
  }

}
