/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ac.blitz.acme;

public class KVIArray {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected KVIArray(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(KVIArray obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ACMEJNI.delete_KVIArray(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public KVIArray() {
    this(ACMEJNI.new_KVIArray__SWIG_0(), true);
  }

  public KVIArray(long n) {
    this(ACMEJNI.new_KVIArray__SWIG_1(n), true);
  }

  public long size() {
    return ACMEJNI.KVIArray_size(swigCPtr, this);
  }

  public long capacity() {
    return ACMEJNI.KVIArray_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    ACMEJNI.KVIArray_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return ACMEJNI.KVIArray_isEmpty(swigCPtr, this);
  }

  public void clear() {
    ACMEJNI.KVIArray_clear(swigCPtr, this);
  }

  public void add(KVI x) {
    ACMEJNI.KVIArray_add(swigCPtr, this, KVI.getCPtr(x), x);
  }

  public KVI get(int i) {
    return new KVI(ACMEJNI.KVIArray_get(swigCPtr, this, i), false);
  }

  public void set(int i, KVI val) {
    ACMEJNI.KVIArray_set(swigCPtr, this, i, KVI.getCPtr(val), val);
  }

}
