/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ac.blitz.acme;

public class KVS {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected KVS(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(KVS obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ACMEJNI.delete_KVS(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType(int value) {
    ACMEJNI.KVS_Type_set(swigCPtr, this, value);
  }

  public int getType() {
    return ACMEJNI.KVS_Type_get(swigCPtr, this);
  }

  public void setValue(String value) {
    ACMEJNI.KVS_Value_set(swigCPtr, this, value);
  }

  public String getValue() {
    return ACMEJNI.KVS_Value_get(swigCPtr, this);
  }

  public KVS() {
    this(ACMEJNI.new_KVS(), true);
  }

}
