/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ac.blitz.acme;

public class KVSArray {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected KVSArray(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(KVSArray obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ACMEJNI.delete_KVSArray(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public KVSArray() {
    this(ACMEJNI.new_KVSArray__SWIG_0(), true);
  }

  public KVSArray(long n) {
    this(ACMEJNI.new_KVSArray__SWIG_1(n), true);
  }

  public long size() {
    return ACMEJNI.KVSArray_size(swigCPtr, this);
  }

  public long capacity() {
    return ACMEJNI.KVSArray_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    ACMEJNI.KVSArray_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return ACMEJNI.KVSArray_isEmpty(swigCPtr, this);
  }

  public void clear() {
    ACMEJNI.KVSArray_clear(swigCPtr, this);
  }

  public void add(KVS x) {
    ACMEJNI.KVSArray_add(swigCPtr, this, KVS.getCPtr(x), x);
  }

  public KVS get(int i) {
    return new KVS(ACMEJNI.KVSArray_get(swigCPtr, this, i), false);
  }

  public void set(int i, KVS val) {
    ACMEJNI.KVSArray_set(swigCPtr, this, i, KVS.getCPtr(val), val);
  }

}
