/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ac.blitz.acme;

public class MediaSessionInfo {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected MediaSessionInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MediaSessionInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ACMEJNI.delete_MediaSessionInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSessionId(String value) {
    ACMEJNI.MediaSessionInfo_SessionId_set(swigCPtr, this, value);
  }

  public String getSessionId() {
    return ACMEJNI.MediaSessionInfo_SessionId_get(swigCPtr, this);
  }

  public void setUserId(String value) {
    ACMEJNI.MediaSessionInfo_UserId_set(swigCPtr, this, value);
  }

  public String getUserId() {
    return ACMEJNI.MediaSessionInfo_UserId_get(swigCPtr, this);
  }

  public void setToken(String value) {
    ACMEJNI.MediaSessionInfo_Token_set(swigCPtr, this, value);
  }

  public String getToken() {
    return ACMEJNI.MediaSessionInfo_Token_get(swigCPtr, this);
  }

  public void setReserved(String value) {
    ACMEJNI.MediaSessionInfo_Reserved_set(swigCPtr, this, value);
  }

  public String getReserved() {
    return ACMEJNI.MediaSessionInfo_Reserved_get(swigCPtr, this);
  }

  public MediaSessionInfo() {
    this(ACMEJNI.new_MediaSessionInfo(), true);
  }

}
