/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ac.blitz.acme;

public final class MediaConfig {
  public final static MediaConfig CONFIG_AGC = new MediaConfig("CONFIG_AGC");
  public final static MediaConfig CONFIG_ACE = new MediaConfig("CONFIG_ACE");
  public final static MediaConfig CONFIG_NS = new MediaConfig("CONFIG_NS");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static MediaConfig swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + MediaConfig.class + " with value " + swigValue);
  }

  private MediaConfig(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private MediaConfig(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private MediaConfig(String swigName, MediaConfig swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static MediaConfig[] swigValues = { CONFIG_AGC, CONFIG_ACE, CONFIG_NS };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

