/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ac.blitz.acme;

public final class MediaPublishStatus {
  public final static MediaPublishStatus MediaPublishStatusStart = new MediaPublishStatus("MediaPublishStatusStart");
  public final static MediaPublishStatus MediaPublishStatusStop = new MediaPublishStatus("MediaPublishStatusStop");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static MediaPublishStatus swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + MediaPublishStatus.class + " with value " + swigValue);
  }

  private MediaPublishStatus(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private MediaPublishStatus(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private MediaPublishStatus(String swigName, MediaPublishStatus swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static MediaPublishStatus[] swigValues = { MediaPublishStatusStart, MediaPublishStatusStop };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

