/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ac.blitz.acme;

public class MediaDump {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected MediaDump(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MediaDump obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ACMEJNI.delete_MediaDump(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType(int value) {
    ACMEJNI.MediaDump_Type_set(swigCPtr, this, value);
  }

  public int getType() {
    return ACMEJNI.MediaDump_Type_get(swigCPtr, this);
  }

  public void setDumps(ChannelDumpArray value) {
    ACMEJNI.MediaDump_Dumps_set(swigCPtr, this, ChannelDumpArray.getCPtr(value), value);
  }

  public ChannelDumpArray getDumps() {
    long cPtr = ACMEJNI.MediaDump_Dumps_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ChannelDumpArray(cPtr, false);
  }

  public MediaDump() {
    this(ACMEJNI.new_MediaDump(), true);
  }

}
