/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ac.blitz.acme;

public class ReceiveAudioStatistics {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ReceiveAudioStatistics(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ReceiveAudioStatistics obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ACMEJNI.delete_ReceiveAudioStatistics(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setRtt(int value) {
    ACMEJNI.ReceiveAudioStatistics_Rtt_set(swigCPtr, this, value);
  }

  public int getRtt() {
    return ACMEJNI.ReceiveAudioStatistics_Rtt_get(swigCPtr, this);
  }

  public void setPlayPacketLoss(int value) {
    ACMEJNI.ReceiveAudioStatistics_PlayPacketLoss_set(swigCPtr, this, value);
  }

  public int getPlayPacketLoss() {
    return ACMEJNI.ReceiveAudioStatistics_PlayPacketLoss_get(swigCPtr, this);
  }

  public void setNetPacketLoss(int value) {
    ACMEJNI.ReceiveAudioStatistics_NetPacketLoss_set(swigCPtr, this, value);
  }

  public int getNetPacketLoss() {
    return ACMEJNI.ReceiveAudioStatistics_NetPacketLoss_get(swigCPtr, this);
  }

  public void setJitter(int value) {
    ACMEJNI.ReceiveAudioStatistics_Jitter_set(swigCPtr, this, value);
  }

  public int getJitter() {
    return ACMEJNI.ReceiveAudioStatistics_Jitter_get(swigCPtr, this);
  }

  public ReceiveAudioStatistics() {
    this(ACMEJNI.new_ReceiveAudioStatistics(), true);
  }

}
