/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ac.blitz.acme;

public class SendVideoStatistics {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SendVideoStatistics(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SendVideoStatistics obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ACMEJNI.delete_SendVideoStatistics(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setFrameRate(int value) {
    ACMEJNI.SendVideoStatistics_FrameRate_set(swigCPtr, this, value);
  }

  public int getFrameRate() {
    return ACMEJNI.SendVideoStatistics_FrameRate_get(swigCPtr, this);
  }

  public void setSendBitrate(int value) {
    ACMEJNI.SendVideoStatistics_SendBitrate_set(swigCPtr, this, value);
  }

  public int getSendBitrate() {
    return ACMEJNI.SendVideoStatistics_SendBitrate_get(swigCPtr, this);
  }

  public void setRttToServer(int value) {
    ACMEJNI.SendVideoStatistics_RttToServer_set(swigCPtr, this, value);
  }

  public int getRttToServer() {
    return ACMEJNI.SendVideoStatistics_RttToServer_get(swigCPtr, this);
  }

  public SendVideoStatistics() {
    this(ACMEJNI.new_SendVideoStatistics(), true);
  }

}
