/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ac.blitz.acme;

public class SendAudioStatistics {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SendAudioStatistics(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SendAudioStatistics obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ACMEJNI.delete_SendAudioStatistics(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setRttToServer(int value) {
    ACMEJNI.SendAudioStatistics_RttToServer_set(swigCPtr, this, value);
  }

  public int getRttToServer() {
    return ACMEJNI.SendAudioStatistics_RttToServer_get(swigCPtr, this);
  }

  public SendAudioStatistics() {
    this(ACMEJNI.new_SendAudioStatistics(), true);
  }

}
