/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ac.blitz.acme;

public final class SessionState {
  public final static SessionState SESSION_STATE_INIT = new SessionState("SESSION_STATE_INIT");
  public final static SessionState SESSION_STATE_ENTERING = new SessionState("SESSION_STATE_ENTERING");
  public final static SessionState SESSION_STATE_ENTERED = new SessionState("SESSION_STATE_ENTERED");
  public final static SessionState SESSION_STATE_LEAVE = new SessionState("SESSION_STATE_LEAVE");
  public final static SessionState SESSION_STATE_ERROR = new SessionState("SESSION_STATE_ERROR");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SessionState swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SessionState.class + " with value " + swigValue);
  }

  private SessionState(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SessionState(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SessionState(String swigName, SessionState swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SessionState[] swigValues = { SESSION_STATE_INIT, SESSION_STATE_ENTERING, SESSION_STATE_ENTERED, SESSION_STATE_LEAVE, SESSION_STATE_ERROR };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

