/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ac.blitz.acme;

public class UInt16Array {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected UInt16Array(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(UInt16Array obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ACMEJNI.delete_UInt16Array(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public UInt16Array() {
    this(ACMEJNI.new_UInt16Array__SWIG_0(), true);
  }

  public UInt16Array(long n) {
    this(ACMEJNI.new_UInt16Array__SWIG_1(n), true);
  }

  public long size() {
    return ACMEJNI.UInt16Array_size(swigCPtr, this);
  }

  public long capacity() {
    return ACMEJNI.UInt16Array_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    ACMEJNI.UInt16Array_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return ACMEJNI.UInt16Array_isEmpty(swigCPtr, this);
  }

  public void clear() {
    ACMEJNI.UInt16Array_clear(swigCPtr, this);
  }

  public void add(int x) {
    ACMEJNI.UInt16Array_add(swigCPtr, this, x);
  }

  public int get(int i) {
    return ACMEJNI.UInt16Array_get(swigCPtr, this, i);
  }

  public void set(int i, int val) {
    ACMEJNI.UInt16Array_set(swigCPtr, this, i, val);
  }

}
