/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ac.blitz.acme;

public class UInt64Array {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected UInt64Array(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(UInt64Array obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ACMEJNI.delete_UInt64Array(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public UInt64Array() {
    this(ACMEJNI.new_UInt64Array__SWIG_0(), true);
  }

  public UInt64Array(long n) {
    this(ACMEJNI.new_UInt64Array__SWIG_1(n), true);
  }

  public long size() {
    return ACMEJNI.UInt64Array_size(swigCPtr, this);
  }

  public long capacity() {
    return ACMEJNI.UInt64Array_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    ACMEJNI.UInt64Array_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return ACMEJNI.UInt64Array_isEmpty(swigCPtr, this);
  }

  public void clear() {
    ACMEJNI.UInt64Array_clear(swigCPtr, this);
  }

  public void add(java.math.BigInteger x) {
    ACMEJNI.UInt64Array_add(swigCPtr, this, x);
  }

  public java.math.BigInteger get(int i) {
    return ACMEJNI.UInt64Array_get(swigCPtr, this, i);
  }

  public void set(int i, java.math.BigInteger val) {
    ACMEJNI.UInt64Array_set(swigCPtr, this, i, val);
  }

}
