/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ac.blitz.acme;

public final class VideoRotation {
  public final static VideoRotation VideoRotation_0 = new VideoRotation("VideoRotation_0", ACMEJNI.VideoRotation_0_get());
  public final static VideoRotation VideoRotation_ClockWise_90 = new VideoRotation("VideoRotation_ClockWise_90");
  public final static VideoRotation VideoRotation_180 = new VideoRotation("VideoRotation_180");
  public final static VideoRotation VideoRotation_ClockWise_270 = new VideoRotation("VideoRotation_ClockWise_270");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static VideoRotation swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + VideoRotation.class + " with value " + swigValue);
  }

  private VideoRotation(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private VideoRotation(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private VideoRotation(String swigName, VideoRotation swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static VideoRotation[] swigValues = { VideoRotation_0, VideoRotation_ClockWise_90, VideoRotation_180, VideoRotation_ClockWise_270 };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

